# - name: Install mxdeployment
#   ansible.builtin.copy:
#     src: "{{ mxpid.mx_deployment }}"
#     dest: "/opt"

# - name: Install mxinfra
#   ansible.builtin.debug:
#     msg: "Install mxinfra"

# - name: Install mxplatform
#   ansible.builtin.debug:
#     msg: "Install mxplatform"

- name: Ensure Metax deployment folder exists
  ansible.builtin.file:
    path: "/opt/mxdeployment"
    state: directory
    mode: 777
