- name: ensure local ssh config folder exists
  delegate_to: localhost
  run_once: true
  ansible.builtin.file:
    path: "{{ ssh_local_folder }}"
    state: directory
    mode: 0777

- name: clear local known_hosts
  delegate_to: localhost
  run_once: true
  ansible.builtin.shell: |
    echo > {{ ssh_local_known_hosts }}

- name: fetch all servers' host keys
  delegate_to: localhost
  run_once: true
  ansible.builtin.shell: |
    ssh-keyscan {{ hostvars[item].ansible_host }} >> {{ ssh_local_known_hosts }} 2>/dev/null
  loop: "{{ groups['all'] }}"

- name: check if local SSH key pair exists
  delegate_to: localhost
  run_once: true
  ansible.builtin.stat:
    path: "{{ ssh_local_private_keyfile }}"
  register: local_pubkey

- name: Generate SSH key pair if not exists
  delegate_to: localhost
  run_once: true
  community.crypto.openssh_keypair:
    path: "{{ ssh_local_private_keyfile }}"
    type: "{{ ssh_key_type }}"
    size: "{{ ssh_key_bits }}"
    state: present
  when: not local_pubkey.stat.exists

- name: Add permissions for files
  delegate_to: localhost
  run_once: true
  ansible.builtin.shell:
    chmod +r {{ ssh_local_folder }}/*

- name: Ensure .ssh directory exists on remote servers
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Upload private key to servers
  ansible.builtin.copy:
    src: "{{ ssh_local_private_keyfile }}"
    dest: "{{ ssh_remote_private_keyfile }}"
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Upload public key to servers
  ansible.builtin.copy:
    src: "{{ ssh_local_public_keyfile }}"
    dest: "{{ ssh_remote_public_keyfile }}"
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Upload authorized keys to server
  ansible.builtin.copy:
    src: "{{ ssh_local_public_keyfile }}"
    dest: "{{ ssh_remote_authorized_keys }}"
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"


- name: Upload known_hosts to server
  ansible.builtin.copy:
    src: "{{ ssh_local_known_hosts }}"
    dest: "{{ ssh_remote_known_hosts }}"
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
