all:
  children:
    calico_rr:
      hosts: {}
    etcd:
      hosts:
        node1: {}
        node2: {}
        node3: {}
    k8s_cluster:
      children:
        kube_control_plane: {}
        kube_node: {}
    kube_control_plane:
      hosts:
        node1: {}
        node2: {}
        node3: {}
    kube_node:
      hosts:
        node1: {}
        node2: {}
        node3: {}
  hosts:
    node1:
      ansible_host: 10.107.204.141
      ip: 10.107.204.141
      access_ip: 10.107.204.141
      ansible_user: metaxadmin
      ansible_password: 'nwrS@Pa55wD'
      ansible_become_password: 'nwrS@Pa55wD'
    node2:
      ansible_host: 10.107.204.142
      ip: 10.107.204.142
      access_ip: 10.107.204.142
      ansible_user: metaxadmin
      ansible_password: 'nwrS@Pa55wD'
      ansible_become_password: 'nwrS@Pa55wD'
    node3:
      ansible_host: 10.107.204.143
      ip: 10.107.204.143
      access_ip: 10.107.204.143
      ansible_user: metaxadmin
      ansible_password: 'nwrS@Pa55wD'
      ansible_become_password: 'nwrS@Pa55wD'
