all:
  hosts:
    node1:
      ansible_host: 192.168.199.101
      ip: 192.168.199.101
      access_ip: 192.168.199.101
      ansible_user: metaxadmin
      ansible_password: "!QAZ2wsx"
      ansible_become_password: "!QAZ2wsx"
    node2:
      ansible_host: 192.168.199.102
      ip: 192.168.199.102
      access_ip: 192.168.199.102
      ansible_user: metaxadmin
      ansible_password: "!QAZ2wsx"
      ansible_become_password: "!QAZ2wsx"
    node3:
      ansible_host: 192.168.199.103
      ip: 192.168.199.103
      access_ip: 192.168.199.103
      ansible_user: metaxadmin
      ansible_password: "!QAZ2wsx"
      ansible_become_password: "!QAZ2wsx"
    node4:
      ansible_host: 192.168.199.104
      ip: 192.168.199.104
      access_ip: 192.168.199.104
      ansible_user: metaxadmin
      ansible_password: "!QAZ2wsx"
      ansible_become_password: "!QAZ2wsx"
    node5:
      ansible_host: 192.168.199.105
      ip: 192.168.199.105
      access_ip: 192.168.199.105
      ansible_user: metaxadmin
      ansible_password: "!QAZ2wsx"
      ansible_become_password: "!QAZ2wsx"

  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
