---
- name: Deploy BNXT RDMA bond rename service
  hosts: kube_node
  become: true
  gather_facts: false

  tasks:

    - name: Copy RDMA rename script
      ansible.builtin.copy:
        src: extra_playbooks/files/bnxt_rename_bond.sh
        dest: /usr/local/sbin/bnxt_rename_bond.sh
        owner: root
        group: root
        mode: '0755'
      notify: Restart RDMA rename service

    - name: Copy systemd service
      ansible.builtin.copy:
        src: extra_playbooks/files/bnxt_rename_bond.service
        dest: /etc/systemd/system/bnxt_rename_bond.service
        owner: root
        group: root
        mode: '0644'
      notify: Restart RDMA rename service

    - name: Enable service
      ansible.builtin.systemd:
        name: bnxt_rename_bond.service
        enabled: true
        daemon_reload: true

    - name: Start service
      ansible.builtin.systemd:
        name: bnxt_rename_bond.service
        state: started

  handlers:

    - name: Restart RDMA rename service
      ansible.builtin.systemd:
        name: bnxt_rename_bond.service
        enabled: true
        state: restarted
        daemon_reload: true
