---
- name: Deploy BNXT RDMA bond rename service
  hosts: kube_node
  become: true
  gather_facts: false

  tasks:
    - name: Copy RDMA rename script
      ansible.builtin.copy:
        src: extra_playbooks/files/bnxt_rename_bond.sh
        dest: /usr/local/sbin/bnxt_rename_bond.sh
        owner: root
        group: root
        mode: '0755'

    - name: Copy systemd service
      ansible.builtin.copy:
        src: extra_playbooks/files/bnxt_rename_bond.service
        dest: /etc/systemd/system/bnxt_rename_bond.service
        owner: root
        group: root
        mode: '0644'

    - name: Enable and restart service (always run script)
      ansible.builtin.systemd:
        name: bnxt_rename_bond.service
        enabled: true
        state: restarted
        daemon_reload: true
